export type FixtureId = "paste" | "VulnerableVault.sol" | "VulnerableAMM.sol" | "SaferAMM.sol";

export type FixtureOption = { id: FixtureId; label: string; hint: string; source: string };

export const FIXTURES: FixtureOption[] = [
  { id: 'paste', label: 'Paste my own code', hint: 'Empty editor', source: '' },
  {
    id: "VulnerableVault.sol",
    label: "Vulnerable vault",
    hint: "Unsafe withdrawals & ownership",
    source: "// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\n/// @notice Intentionally vulnerable vault for GuardScan demo fixtures.\n/// @dev DO NOT deploy on mainnet. Used only as a scanner true-positive target.\ncontract VulnerableVault {\n    mapping(address => uint256) public balances;\n    address public owner;\n\n    constructor() {\n        owner = msg.sender;\n    }\n\n    function deposit() external payable {\n        balances[msg.sender] += msg.value;\n    }\n\n    /// @dev Missing access control: anyone can take ownership.\n    function setOwner(address newOwner) external {\n        owner = newOwner;\n    }\n\n    /// @dev tx.origin auth anti-pattern.\n    function privilegedWithdraw() external {\n        require(tx.origin == owner, \"not owner\");\n        uint256 amount = address(this).balance;\n        (bool ok, ) = payable(msg.sender).call{value: amount}(\"\");\n        require(ok, \"send failed\");\n    }\n\n    /// @dev Classic reentrancy: external call before state update.\n    function withdraw() external {\n        uint256 amount = balances[msg.sender];\n        require(amount > 0, \"no balance\");\n        (bool ok, ) = payable(msg.sender).call{value: amount}(\"\");\n        require(ok, \"send failed\");\n        balances[msg.sender] = 0;\n    }\n}\n",
  },
  {
    id: "VulnerableAMM.sol",
    label: "Vulnerable AMM",
    hint: "Unsafe token swap",
    source: "// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\ninterface IERC20Like {\n    function transfer(address to, uint256 amount) external returns (bool);\n    function transferFrom(address from, address to, uint256 amount) external returns (bool);\n    function approve(address spender, uint256 amount) external returns (bool);\n}\n\n/// @notice Intentionally vulnerable AMM-style swap for GuardScan demo fixtures.\n/// @dev DO NOT deploy on mainnet. Used only as a scanner true-positive target.\ncontract VulnerableAMM {\n    IERC20Like public token0;\n    IERC20Like public token1;\n    uint256 public reserve0;\n    uint256 public reserve1;\n    address public owner;\n\n    constructor(address t0, address t1) {\n        token0 = IERC20Like(t0);\n        token1 = IERC20Like(t1);\n        owner = msg.sender;\n    }\n\n    /// @dev Missing access control on a sensitive admin function.\n    function setReserves(uint256 r0, uint256 r1) external {\n        reserve0 = r0;\n        reserve1 = r1;\n    }\n\n    /// @dev Swap without slippage protection (no minOut / amountOutMin).\n    function swap(address tokenIn, uint256 amountIn) external returns (uint256 amountOut) {\n        require(amountIn > 0, \"zero in\");\n        bool isToken0 = tokenIn == address(token0);\n        require(isToken0 || tokenIn == address(token1), \"bad token\");\n\n        // Simplified constant-product style quote (toy math, not production).\n        if (isToken0) {\n            amountOut = (amountIn * reserve1) / (reserve0 + amountIn);\n            token0.transferFrom(msg.sender, address(this), amountIn);\n            // Unsafe: ignore ERC-20 return value.\n            token1.transfer(msg.sender, amountOut);\n            reserve0 += amountIn;\n            reserve1 -= amountOut;\n        } else {\n            amountOut = (amountIn * reserve0) / (reserve1 + amountIn);\n            token1.transferFrom(msg.sender, address(this), amountIn);\n            token0.transfer(msg.sender, amountOut);\n            reserve1 += amountIn;\n            reserve0 -= amountOut;\n        }\n    }\n\n    /// @dev Infinite approval anti-pattern.\n    function approveRouter(address router) external {\n        token0.approve(router, type(uint256).max);\n        token1.approve(router, type(uint256).max);\n    }\n}\n",
  },
  {
    id: "SaferAMM.sol",
    label: "Hardened AMM",
    hint: "Same swap, flagged issues fixed",
    source: "// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\ninterface IERC20Like {\n    function transfer(address to, uint256 amount) external returns (bool);\n    function transferFrom(address from, address to, uint256 amount) external returns (bool);\n}\n\n/// @notice Safer-ish AMM-style swap snippet for GuardScan contrast fixture.\n/// @dev Still educational \u2014 not production-ready DeFi.\ncontract SaferAMM {\n    IERC20Like public token0;\n    IERC20Like public token1;\n    uint256 public reserve0;\n    uint256 public reserve1;\n    address public owner;\n\n    modifier onlyOwner() {\n        require(msg.sender == owner, \"not owner\");\n        _;\n    }\n\n    constructor(address t0, address t1) {\n        token0 = IERC20Like(t0);\n        token1 = IERC20Like(t1);\n        owner = msg.sender;\n    }\n\n    function setReserves(uint256 r0, uint256 r1) external onlyOwner {\n        reserve0 = r0;\n        reserve1 = r1;\n    }\n\n    /// @notice Swap with minOut slippage guard and checks-effects-interactions style updates.\n    function swap(address tokenIn, uint256 amountIn, uint256 minOut) external returns (uint256 amountOut) {\n        require(amountIn > 0, \"zero in\");\n        bool isToken0 = tokenIn == address(token0);\n        require(isToken0 || tokenIn == address(token1), \"bad token\");\n\n        if (isToken0) {\n            amountOut = (amountIn * reserve1) / (reserve0 + amountIn);\n            require(amountOut >= minOut, \"slippage\");\n            reserve0 += amountIn;\n            reserve1 -= amountOut;\n            require(token0.transferFrom(msg.sender, address(this), amountIn), \"transferFrom failed\");\n            require(token1.transfer(msg.sender, amountOut), \"transfer failed\");\n        } else {\n            amountOut = (amountIn * reserve0) / (reserve1 + amountIn);\n            require(amountOut >= minOut, \"slippage\");\n            reserve1 += amountIn;\n            reserve0 -= amountOut;\n            require(token1.transferFrom(msg.sender, address(this), amountIn), \"transferFrom failed\");\n            require(token0.transfer(msg.sender, amountOut), \"transfer failed\");\n        }\n    }\n}\n",
  },
];

export function fixtureById(id: FixtureId): FixtureOption {
  return FIXTURES.find((f) => f.id === id) ?? FIXTURES[0];
}
